export const ADD_BOOKING = "ADD_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";


export const ADD_USER = "ADD_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_ERROR_USER = "LOGIN_ERROR_USER";
export const LOGIN_ERROR_WRONGINPUT_USER = "LOGIN_ERROR_WRONGINPUT_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const CLEAR_ERROR = "CLEAR_ERROR";


//GET ARRAY FOR BOOKING VENUE AND TIMESLOT
export const GET_BOOKING_ARRAY = "GET_BOOKING_ARRAY";

//GET BOOKED LIST FROM DATABASE
export const GET_BOOKED_DATA = "GET_BOOKED_DATA";

//TO DELETE BOOKED LIST FROM DATABASE
export const DELETE_DATA = "DELETE_DATA";

//GET APPROVED BOOKING LIST FROM DADTABASE
export const GET_APPROVED_BOOKING_DATA = "GET_APPROVED_BOOKING_DATA";